# Alpha profile
# Run with: --spring.profiles.active=alpha

spring.datasource.url=${ALPHA_DB_URL:jdbc:mysql://localhost:3306/vizo_alpha?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${ALPHA_DB_USER:root}
spring.datasource.password=${ALPHA_DB_PASS:12345678}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.thymeleaf.cache=true

logging.level.root=INFO
logging.level.com.vitrung.vizo_dong=INFO
