# Production profile
# Run with: --spring.profiles.active=prod

spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USER}
spring.datasource.password=${PROD_DB_PASS}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.thymeleaf.cache=true

logging.level.root=WARN
logging.level.com.vitrung.vizo_dong=INFO
