# Staging profile
# Run with: --spring.profiles.active=stg

spring.datasource.url=${STG_DB_URL:jdbc:mysql://localhost:3306/vizo_stg?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${STG_DB_USER:root}
spring.datasource.password=${STG_DB_PASS:12345678}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.thymeleaf.cache=true

logging.level.root=INFO
logging.level.com.vitrung.vizo_dong=INFO
